config/routes.rb
GoalSetterApp::Application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]
  resources :goals
  resources :comments, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author_id, :body, :commentable_id, :commentable_type, presence: true

  belongs_to :commentable, polymorphic: true
  belongs_to :author, class_name: "User", foreign_key: :author_id
end

app/models/concerns/commentable.rb
require 'active_support/concern'

module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable

  validates :name, :user_id, :privacy, presence: true
  validates :completed, inclusion: { in: [true, false] }
  validates :privacy, inclusion: { in: ["private", "public"] }

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Commentable

  attr_reader :password

  validates :username, presence: true, uniqueness: true
  validates :session_token, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  has_many :goals
  has_many :authored_comments, class_name: "Comment", foreign_key: :author_id

  def self.find_by_credentials(username, password)
    @user = User.find_by_username(username)
    @user.try(:is_password?, password) ? @user : nil
  end

  def password=(plain_text)
    @password = plain_text
    self.password_digest = BCrypt::Password.create(plain_text)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def is_password?(plain_text)
    BCrypt::Password.new(self.password_digest).is_password?(plain_text)
  end

  def find_index_goals
    Goal.where("goals.privacy = 'public' OR goals.user_id = ?", self.id)
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  helper_method :current_user, :signed_in?, :get_auth_token

  def get_auth_token
    "<input type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to @comment.commentable
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to @comment.commentable
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment)
      .permit(:author_id, :body, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def new
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.completed = false
    @goal.user_id = current_user.id

    if @goal.save

      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render user_url(current_user)
    end
  end

  def edit
  end

  def update
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def index
    @goals = current_user.find_index_goals
  end

  def destroy
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :description, :privacy, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_signed_in, only: :destroy

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password])
    if @user.nil?
      flash.now[:errors] = ['credentials were incorrect']
      render :new
    else
      sign_in!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_in, except: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def sign_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def ensure_signed_in
    redirect_to new_session_url unless signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.body %><br>
by <%= comment.author.username %></p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/goals/_goal.html.erb
<strong>Goal <%= goal_num + 1 %>. <%= goal.name %></strong>
<ul>
  <li>User: <%= goal.user.username %></li>
  <li><%= goal.description %></li>
  <li><%= goal.privacy %></li>
  <li><%= goal.completed %></li>
</ul>

app/views/goals/_new.html.erb
<h3>New Goal:</h3>

<form action="<%= goals_url %>" method="post" accept-charset="utf-8">
  <%= get_auth_token %>

  <label for="name">Name</label>
  <input type="text" name="goal[name]" value="" id="name">
  <br>
  <select name="goal[privacy]" id="goal_privacy">
    <option value="public">Public</option>
    <option value="private">Private</option>
  </select>

  <label for="description">Description</label>
  <input type="text" name="goal[description]" value="" id="description">
  <br>




  <p><input type="submit" value="Create Goal"></p>
</form>

app/views/goals/create.html.erb
<h1>Goals#create</h1>
<p>Find me in app/views/goals/create.html.erb</p>

app/views/goals/destroy.html.erb
<h1>Goals#destroy</h1>
<p>Find me in app/views/goals/destroy.html.erb</p>

app/views/goals/edit.html.erb
<h1>Goals#edit</h1>
<p>Find me in app/views/goals/edit.html.erb</p>

app/views/goals/index.html.erb
<h1>Goals#index</h1>

<% @goals.each_with_index do |goal, n| %>
  <%= render partial: goal, locals: { goal: goal, goal_num: n } %>
<% end%>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<p>Find me in app/views/goals/show.html.erb</p>

<%= render @goal.comments %>
<h3>Add Comment:</h3>
<%= render partial: "shared/comment_form",
  locals: { id: @goal.id, type: "Goal"} %>

app/views/goals/update.html.erb
<h1>Goals#update</h1>
<p>Find me in app/views/goals/update.html.erb</p>

app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if signed_in? %>
    <%= current_user.username %>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_session_url %>
    <%= link_to "Sign Up", new_user_url %>
  <% end %>

  <%= render "layouts/errors" %>

  <%= yield %>

</body>
</html>

app/views/shared/_comment_form.html.erb
<form action="<%= comments_url %>" method="post" accept-charset="utf-8">
  <%= get_auth_token %>
  <label for="comment">Comment</label><input type="text" name="comment[body]" value="" id="comment">
  <input type="hidden" name="comment[commentable_id]" value="<%= id %>" id="comment[commentable_id]">
  <input type="hidden" name="comment[commentable_type]" value="<%= type %>" id="comment[commentable_type]">

  <p><input type="submit" value="Add Comment"></p>
</form>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post" accept-charset="utf-8">
  <%= get_auth_token %>
  <label for="username">Username</label>
  <input type="text" name="user[username]" value="" id="username">
  <br>
  <label for="password">Password</label>
  <input type="password" name="user[password]" value="" id="password">
  <br>
  <p><input type="submit" value="Sign Up"></p>
</form>

app/views/users/show.html.erb
<h1>Users#show</h1>

<% @user.goals.each_with_index do |goal, n| %>
  <%= render partial: goal, locals: { goal: goal, goal_num: n } %>
<% end%>

<%= render "/goals/new" %>
<%= render @user.comments %>
<h3>Add Comment:</h3>
<%= render partial: "shared/comment_form",
  locals: { id: @user.id, type: "User"} %>